---
version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    expose:
      - 2181
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "orders:5:1"
    expose:
      - 9092
  order:
    image: node:14-alpine
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    volumes:
      - ./order-service/:/usr/src/app/
    command: 'node index.js'
    depends_on:
      - kafka
  invoice:
    image: node:14-alpine
    working_dir: /usr/src/app
    volumes:
      - ./invoice-service/:/usr/src/app/
    command: 'node index.js'
    depends_on:
      - kafka
      - order